language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.1
    - android-28
    - extra-android-m2repository

before_install:
- yes | sdkmanager "platforms;android-28"

script:
 - ./gradlew clean build
